### ISSUE TITLE
lang_or_pipeline argument of textacy.TextCorpus.from_texts() does not accept 'en' or {'en', 'de'} per docstring

### ISSUE THREAD

**Issue by stong1108** [chartbeat-labs/textacy#33]
I had trouble building a corpus using the `textacy.TextCorpus.from_texts()` function and could not get it to work using `'en'` or `{'en', 'de'}` as the first argument (specified in documentation shown below).

```
Docstring:
Convenience function for creating a :class:`TextCorpus <textacy.texts.TextCorpus>`
from an iterable of text strings.

Args:
    lang_or_pipeline ({'en', 'de'} or :class:`spacy.<lang>.<Language>`)
    texts (iterable(str))
    metadata (iterable(dict), optional)
    n_threads (int, optional)
    batch_size (int, optional)
```
When running either of the commands 
`corpus = textacy.TextCorpus.from_texts('en', iterdocs)`
or 
`corpus = textacy.TextCorpus.from_texts({'en', 'de'}, iterdocs)`

as suggested by the documentation, I get the errors:

`AttributeError: 'str' object has no attribute 'lang'`
or
`AttributeError: 'set' object has no attribute 'lang'`

I was able to build my corpus using a spacy language class instead with:
`corpus = textacy.TextCorpus.from_texts(spacy.en.English(), iterdocs)`

Was the use of `'en'` or `{'en', 'de'}` a misinterpretation of the documentation on my part?

I also tried `en` (without quotes) just in case.

**Comment by bdewilde** [comment]
Hi @stong1108 , sorry about the docstring confusion: When only a small set of strings are possible param values, I usually just write them out as is done in `TextCorpus.from_texts()`. As explained in the class docstring itself — but not in this method, unfortunately — the options are either 'en', 'de', or a corresponding spacy pipeline object, and _not_ `{'en', 'de'}`.

I was unable to replicate your error using `corpus = textacy.TextCorpus.from_texts('en', iterdocs)`. For example:

```pycon
>>> import textacy
>>> texts = ['This is a text.', 'And here is another.']
>>> textacy.TextCorpus.from_texts('en', texts)
TextCorpus(2 docs; 10 tokens)
```

That worked in both Python 3.5 and 2.7 (after ensuring that the latter's text strings were unicode). Could you send a full code sample, as well as the full exception traceback? Also, just to double-check: Which version of Python are you using? Which version of `textacy`? And which OS?

**Comment by bdewilde** [comment]
Hi again, just a quick follow-up: I _think_ that your error could arise if you're using `textacy < 0.2.8` (anything other than the latest version, released today) and pass in a bytes string for the language param, which is very easy to do in Python 2. This would cause an error because, previously, the code checked if the parameter was a unicode string, and if not it assumed that it was a spaCy language pipeline.

**Comment by stong1108** [comment]
Thanks for the quick response @bdewilde -  yup, I was using `textacy 0.2.5` in IPython 4.0.1, Python 2.7.11, on OS X Yosemite 10.10.2.

Here's a reproduction of the error with the 0.2.5 package (and now also 0.2.8):
```
In [1]: import textacy

In [2]: texts = ['This is a text.', 'And here is another.']

In [3]: textacy.TextCorpus.from_texts('en', texts)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-f0b7223a29f6> in <module>()
----> 1 textacy.TextCorpus.from_texts('en', texts)

/Users/stong/anaconda/lib/python2.7/site-packages/textacy/texts.pyc in from_texts(cls, lang_or_pipeline, texts, metadata, n_threads, batch_size)
    864             :class:`TextCorpus <textacy.texts.TextCorpus>`
    865         """
--> 866         textcorpus = cls(lang_or_pipeline)
    867         spacy_docs = textcorpus.spacy_pipeline.pipe(
    868             texts, n_threads=n_threads, batch_size=batch_size)

/Users/stong/anaconda/lib/python2.7/site-packages/textacy/texts.pyc in __init__(self, lang_or_pipeline)
    755         else:
    756             self.spacy_pipeline = lang_or_pipeline
--> 757             self.lang = self.spacy_pipeline.lang
    758         self.spacy_vocab = self.spacy_pipeline.vocab
    759         self.spacy_stringstore = self.spacy_vocab.strings

AttributeError: 'str' object has no attribute 'lang'
```

I ran `pip install textacy -U` to upgrade to 0.2.8; however `textacy.__version__` still returns `'0.2.5'`, which is what I see in the `__init__.py` for the 0.2.8 version.

I thought somehow I hadn't upgraded to 0.2.8 with my previous command, so I decided to try uninstalling then re-installing. But, after executing `pip uninstall textacy`, the first line my terminal printed was `Uninstalling textacy-0.2.8:`... I'm stumped.

**Comment by stong1108** [comment]
Sorry, I was mistaken- I got a unicode error in 0.2.8 running the code you provided. 

I wasn't able to replicate your code using strings, but it works as expected after casting unicode.

Using string input: 
```
In [1]: import textacy

In [2]: texts = ['This is a text.', 'And here is another.']

In [3]: textacy.TextCorpus.from_texts('en', texts)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-f0b7223a29f6> in <module>()
----> 1 textacy.TextCorpus.from_texts('en', texts)

/Users/stong/anaconda/lib/python2.7/site-packages/textacy/texts.pyc in from_texts(cls, lang_or_pipeline, texts, metadata, n_threads, batch_size)
    892                                            metadata=md))
    893         else:
--> 894             for spacy_doc in spacy_docs:
    895                 textcorpus.add_doc(TextDoc(spacy_doc, lang=textcorpus.lang,
    896                                            spacy_pipeline=textcorpus.spacy_pipeline,

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/language.pyc in pipe(self, texts, tag, parse, entity, n_threads, batch_size)
    254             stream = self.entity.pipe(stream,
    255                 n_threads=1, batch_size=batch_size)
--> 256         for doc in stream:
    257             yield doc
    258

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/syntax/parser.pyx in pipe (spacy/syntax/parser.cpp:6529)()
    127         cdef int status
    128         queue = []
--> 129         for doc in stream:
    130             doc_ptr[len(queue)] = doc.c
    131             lengths[len(queue)] = doc.length

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/syntax/parser.pyx in pipe (spacy/syntax/parser.cpp:6529)()
    127         cdef int status
    128         queue = []
--> 129         for doc in stream:
    130             doc_ptr[len(queue)] = doc.c
    131             lengths[len(queue)] = doc.length

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/matcher.pyx in pipe (spacy/matcher.cpp:8179)()
    237
    238     def pipe(self, docs, batch_size=1000, n_threads=2):
--> 239         for doc in docs:
    240             self(doc)
    241             yield doc

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/tagger.pyx in pipe (spacy/tagger.cpp:6283)()
    213
    214     def pipe(self, stream, batch_size=1000, n_threads=2):
--> 215         for doc in stream:
    216             self(doc)
    217             yield doc

/Users/stong/anaconda/lib/python2.7/site-packages/spacy/tokenizer.pyx in pipe (spacy/tokenizer.cpp:5133)()
    136     def pipe(self, texts, batch_size=1000, n_threads=2):
    137         for text in texts:
--> 138             yield self(text)
    139
    140     cdef int _try_cache(self, hash_t key, Doc tokens) except -1:

TypeError: Argument 'string' has incorrect type (expected unicode, got str)
```

Using unicode input:
```
In [7]: texts = [unicode(txt) for txt in texts]

In [8]: texts
Out[8]: [u'This is a text.', u'And here is another.']

In [9]: textacy.TextCorpus.from_texts('en', texts)
Out[9]: TextCorpus(2 docs; 10 tokens)
```

**Comment by bdewilde** [comment]
Hi @stong1108 , thanks for pointing that out: I totally forgot to change `__version__` to 0.2.8 in the init file. My bad!

As for the the second error you mentioned: That is expected behavior. `spaCy` only works with unicode texts, so `textacy` only works with unicode texts. Certain other strings — such as the lang param used to initialize a `TextCorpus` — can be either unicode or bytes because it doesn't affect anything, but the text content itself must always be unicode. I've been meaning to make this more clear in the documentation: Everywhere I write `str`, I mean a Python 3 `str`, which is actually `unicode` in Python 2. I've developed the code in Py3 and only switch to Py2 to run tests so this makes sense to me, but I understand that not everybody is able or willing to upgrade yet.

Sorry about all the confusion, I'll make a couple tweaks to address it as soon as I can.

**Comment by stong1108** [comment]
Gotcha. Thanks for the clarification about Python 3 vs. Python 2 string/unicode, did not know!
