### ISSUE TITLE
normalize_hyphenated_words() not working in version 0.11.0

### ISSUE THREAD

**Issue by AShahLab** [chartbeat-labs/textacy#356]
### steps to reproduce

1. Open Colab and use `!pip install textacy`
2. `import textacy.preprocessing as tprep`
3. `tprep.normalize_hyphenated_words(text)` throws an error that `AttributeError: module 'textacy.preprocessing' has no attribute 'normalize_hyphenated_words'`

- operating system:
- python version:
- `spacy` version: **3.2.2**
- installed `spacy` models: **spacy, spacy-legacy, spacy-loggers**
- `textacy` version:**0.11.0**

**Comment by bdewilde** [comment]
Hi @AShahLab , that function is available at `textacy.preprocessing.normalize.hyphenated_words()` (docs: https://textacy.readthedocs.io/en/latest/api_reference/preprocessing.html#normalize). It was moved in v0.11 (release notes: https://github.com/chartbeat-labs/textacy/releases/tag/0.11.0). The underlying functionality is the same.
